version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3003:80"
    restart: always

  server:
    build:
      context: ./server
    ports:
      - "5003:5003"
    env_file:
      - ./server/.env
    restart: always
